[mypy]
ignore_missing_imports = False

[mypy-telethon]
ignore_missing_imports = True

[mypy-telethon.*]
ignore_missing_imports = True

[mypy-telethon.*.*]
ignore_missing_imports = True

[mypy-telethon.*.*.*]
ignore_missing_imports = True

[mypy-tgcrypto]
ignore_missing_imports = True
